thrust: assignment_thrust.cu
	nvcc assignment_thrust.cu -ccbin g++ -std=c++11 -o assignment_thrust.exe

npp_nvgraph: assignment_npp_nvgraph.cu
	nvcc assignment_npp_nvgraph.cu -ccbin g++ -std=c++11 -o assignment_npp_nvgraph.exe